{% set name = "palantir-sdk" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 72b75854e66ca4e8cebcdb22b8c2d3ab7afd21423c03e811bf2a9ce0a5ec76b1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry

  run:
    - python >={{ python_min }}
    - tomli
    - conjure-python-client >=2.1.0,<3

test:
  requires:
    - python {{ python_min }}
  imports:
    - palantir

about:
  home: https://pypi.org/project/palantir-sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Palantir Python SDK

extra:
  recipe-maintainers:
    - ahggns
    - tom-s-powell
    - AlexandreGuinaudeau
