{% set name = "palantir-sdk" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ba11a7c7b4bf69074a52a57d3b23b077089f1d55699d09b125905b8ba6e547f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry

  run:
    - python >=3.8
    - tomli
    - conjure-python-client >=2.1.0,<3

test:
  imports:
    - palantir

about:
  home: https://pypi.org/project/palantir-sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Palantir Python SDK

extra:
  recipe-maintainers:
    - ahggns
    - tom-s-powell
    - AlexandreGuinaudeau
